### ISSUE TITLE
Epic to consolidate shortcut issues

### ISSUE THREAD

**Issue by caesay** [velopack/velopack#118]
- [ ] Ability to set AUMID at vpk pack time for all shortcuts created (probably rust and dotnet) #104 
- [ ] Use COM RemoveFromList before removing .lnk files or you can end up with broken shortcuts in taskbar #100 
- [x] Shortcuts being deleted for related but different apps on uninstall #93 
- [x] ~~Review the shortcut creation behavior on migration #94~~ wontfix
- [ ] Shortcuts not updated when --packTitle or icon changes #67 
- [ ] Configure shortcut locations in vpk pack #46 
- [x] ~~Add `ShortcutLocations.TaskBar` target to the `--shortcuts` argument. Will not be supported via legacy classes but can perform the taskbar prompt in Setup/Update via `RequestPinCurrentAppAsync`~~ Won't do because it is not supported for desktop apps (you need to ship/install an appx)
