### ISSUE TITLE
Responsive Hooks 

### ISSUE THREAD

**Issue by caesay** [velopack/velopack#303]
It's clear that the current implementation of hooks has many limitations and there are regular requests to improve them. 
- Sometimes it's just not possible (or is extremely difficult) to implement them (eg. Unity). 
- Sometimes the arbitrary hook timeouts (15 and 30s) are too short for legitimate use-cases 
- Elongating or removing the hook timeouts will not work, because there is no progress response to the user - or worse, if the program has not implemented hooks or is hung, it will also hang the install/update/uninstall processes.
- Because of the timeouts, it is not possible to show UI or ask for user feedback
- It's not possible to abort a process, for example an install, update, or uninstall during a hook execution

If the child process (handling hooks) could communicate to the parent process, we could solve some of these issues. For example, we could allow the hooks to run indefinitely (or with a 5min hard timeout) but require regular health pings. If we do not receive a ping during a given 10 second interval, we can assume the process is hung and terminate it. Additionally, if there is a communication pipe avaliable, the child process could report progress to be shown as a part of the overall operation progress - and "cancel" or "rollback" messages could be sent to interrupt the operation entirely (like aborting an uninstall).

We can not utilize stdin/stdout for this, since Velopack does not entirely control the child process and we can not guarantee that other messages will not be written. If we utilize unnamed pipes or local sockets (via the [interprocess crate](https://docs.rs/interprocess/latest/interprocess/unnamed_pipe/fn.pipe.html), for example) we could pass the handle to a pipe via an environment variable and use this for efficient communication.

- [ ] Add an opt-in (`--enable-hooks`) or opt-out (`--disable-hooks`) to `vpk pack` to support cases like Unity. An opt-in would make this migration to the new format easier, since if people update vpk but forget to upgrade their library, the result will just be that hooks don't run. In the opt-out case, vpk will try to run the hooks that the library does not understand and result in weird behavior and killed processes.
- [ ] Implement `interprocess` to create an unnamedpipe and pass the handle to child process as an environment variable
- [ ] Allow heartbeat, progress and cancellation messages to be sent from the client to the parent

Supersedes #297 #127

**Comment by bastianschildknecht** [comment]
Any update on this?

**Comment by caesay** [comment]
This issue is something we want to do but is not currently prioritised so I can't give you an idea on when it is coming.

**Comment by bastianschildknecht** [comment]
> This issue is something we want to do but is not currently prioritised so I can't give you an idea on when it is coming.

I understand, thank you anyway. 
Is there any workaround for the time being?

**Comment by caesay** [comment]
Ultimately you're going to need a binary which contains the velopack library - so you can do updates and so forth. If you are wrapping some dumb exe you dont control, then the workaround is to deploy a second launcher exe, which handles hooks, updates, and so forth, and then just launches the dumb exe afterwards. Point vpk at the new launcher exe instead of the dumb one.

**Comment by bastianschildknecht** [comment]
> Ultimately you're going to need a binary which contains the velopack library - so you can do updates and so forth. If you are wrapping some dumb exe you dont control, then the workaround is to deploy a second launcher exe, which handles hooks, updates, and so forth, and then just launches the dumb exe afterwards. Point vpk at the new launcher exe instead of the dumb one.

Alright thanks! 👍
